//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Исхакова_Глазки_save
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSale
    {
        public int ID { get; set; }
        public int AgentID { get; set; }
        public int ProductID { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int ProductCount { get; set; }

        public string Datacount
        {
            get
            {
                string product = Product.Title;
                string data = Convert.ToString(SaleDate);
                string count = Convert.ToString(ProductCount);
                string dc =product + " " + data + " " + count;
                return dc;
            }
        }
        public decimal Cost
        {
            get
            {
                return Product.MinCostForAgent * this.ProductCount;
            }
        }

        public virtual Agent Agent { get; set; }
        public virtual Product Product { get; set; }
    }
}
